#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.
D="$(date +%d-%m-%Y)"
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -zcvf "$D".tar.gz ./backup.sql
