#!/usr/bin/env bash
#manages manage_my_process
case "$1" in
	"start")
		./manage_my_process &
		pgrep -f manage_my_process > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	"stop")
		pkill -f manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	"restart")
		pkill -f manage_my_process
		rm /var/run/my_process.pid
		./manage_my_process
		pgrep -f manage_my_process > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
