#!/usr/bin/env bash
#Ubuntu server with localhost 127.0.0.2 and facebook.com as 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i '1s/^/8.8.8.8       facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
