#!/usr/bin/env bash
# improvment server
pkill apache2
chown -R nginx:nginx /etc/nginx/
chmod 666 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
su - nginx -c 'service nginx start'
