#!/usr/bin/env bash
# fix server
pkill apache2
chmod 666 /etc/nginx/nginx.conf
sed -i '1s/^/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
su - nginx -c 'service nginx start'
